---
- name: Przygotowanie Srodowiska DevOps
  hosts: local
  become: yes
  tasks:
    - name: Aktualizacja cache apt
      apt:
        update_cache: yes

    - name: Instalacja Dockera
      shell: curl -fsSL https://get.docker.com | sh
      args:
        creates: /usr/bin/docker

    - name: Dodanie uzytkownika do grupy docker
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    - name: Instalacja K3s (Kubernetes)
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s
